name: OpenAIAgent(gpt-4o)

agent:
  name: OpenAIAgent
  args:
    api_key: xxxx
    # api_base: xxxx
    model_name: gpt-4o
    max_new_tokens: 512

task:
  class: TextOnlyMobileTask_AutoTest
  args:
    save_dir: "./logs/evaluation_openai_agent"
    max_rounds: 25
    request_interval: 3
    mode: "in_app"

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060


