name: MobileUseMultiAgent

agent:
    name: MobileUseAgent
    args:
      vllm_config:
        model_name: qwen2.5-vl-72b-instruct
        api_key: xxxxx
        base_url: xxxxx
        max_tokens: 1024
      agent_config:
        type: MultiAgent
        use_note_taker: false
        use_planner: false
        use_reflector: true
        use_long_reflector: true
        evaluate_when_finish: true
        use_processor: true

task:
    class: MobileUse_AutoTest
    args:
        save_dir: "./logs/evaluation_mobile_use"
        max_rounds: 25
        request_interval: 3

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060
